/*
 * This file is generated by jOOQ.
 */
package hr.tvz.financije.repositories.entities.jooq;


import hr.tvz.financije.repositories.entities.jooq.tables.Account;
import hr.tvz.financije.repositories.entities.jooq.tables.Category;
import hr.tvz.financije.repositories.entities.jooq.tables.Currency;
import hr.tvz.financije.repositories.entities.jooq.tables.Profile;
import hr.tvz.financije.repositories.entities.jooq.tables.Record;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.currency</code>.
     */
    public final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>public.profile</code>.
     */
    public final Profile PROFILE = Profile.PROFILE;

    /**
     * The table <code>public.record</code>.
     */
    public final Record RECORD = Record.RECORD;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            Category.CATEGORY,
            Currency.CURRENCY,
            Profile.PROFILE,
            Record.RECORD
        );
    }
}
