/*
 * This file is generated by jOOQ.
 */
package hr.tvz.financije.repositories.entities.jooq;


import hr.tvz.financije.repositories.entities.jooq.tables.Account;
import hr.tvz.financije.repositories.entities.jooq.tables.Category;
import hr.tvz.financije.repositories.entities.jooq.tables.Currency;
import hr.tvz.financije.repositories.entities.jooq.tables.Profile;
import hr.tvz.financije.repositories.entities.jooq.tables.Record;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.currency</code>.
     */
    public static final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>public.profile</code>.
     */
    public static final Profile PROFILE = Profile.PROFILE;

    /**
     * The table <code>public.record</code>.
     */
    public static final Record RECORD = Record.RECORD;
}
