/*
 * This file is generated by jOOQ.
 */
package hr.tvz.financije.repositories.models.jooq;


import hr.tvz.financije.repositories.models.jooq.tables.Record;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RECORD_TYPE_RECORD_DATE_IDX = Internal.createIndex(DSL.name("record_type_record_date_idx"), Record.RECORD, new OrderField[] { Record.RECORD.TYPE, Record.RECORD.RECORD_DATE }, false);
}
