/*
 * This file is generated by jOOQ.
 */
package hr.tvz.financije.repositories.models.jooq.tables.records;


import hr.tvz.financije.repositories.models.jooq.tables.Category;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRecord extends UpdatableRecordImpl<CategoryRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.category.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.category.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.category.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.category.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.category.icon</code>.
     */
    public void setIcon(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.category.icon</code>.
     */
    public String getIcon() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.category.color</code>.
     */
    public void setColor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.category.color</code>.
     */
    public String getColor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.category.profile_id</code>.
     */
    public void setProfileId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.category.profile_id</code>.
     */
    public Integer getProfileId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Category.CATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return Category.CATEGORY.NAME;
    }

    @Override
    public Field<String> field3() {
        return Category.CATEGORY.ICON;
    }

    @Override
    public Field<String> field4() {
        return Category.CATEGORY.COLOR;
    }

    @Override
    public Field<Integer> field5() {
        return Category.CATEGORY.PROFILE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getIcon();
    }

    @Override
    public String component4() {
        return getColor();
    }

    @Override
    public Integer component5() {
        return getProfileId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getIcon();
    }

    @Override
    public String value4() {
        return getColor();
    }

    @Override
    public Integer value5() {
        return getProfileId();
    }

    @Override
    public CategoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CategoryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CategoryRecord value3(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public CategoryRecord value4(String value) {
        setColor(value);
        return this;
    }

    @Override
    public CategoryRecord value5(Integer value) {
        setProfileId(value);
        return this;
    }

    @Override
    public CategoryRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryRecord
     */
    public CategoryRecord() {
        super(Category.CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    public CategoryRecord(Integer id, String name, String icon, String color, Integer profileId) {
        super(Category.CATEGORY);

        setId(id);
        setName(name);
        setIcon(icon);
        setColor(color);
        setProfileId(profileId);
        resetChangedOnNotNull();
    }
}
