/*
 * This file is generated by jOOQ.
 */
package hr.tvz.financije.repositories.entities.jooq.tables.records;


import hr.tvz.financije.repositories.entities.jooq.tables.Record;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecordRecord extends UpdatableRecordImpl<RecordRecord> implements Record8<Integer, Long, String, LocalDateTime, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.record.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.record.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.record.amount</code>.
     */
    public void setAmount(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.record.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.record.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.record.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.record.record_date</code>.
     */
    public void setRecordDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.record.record_date</code>.
     */
    public LocalDateTime getRecordDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.record.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.record.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.record.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.record.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.record.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.record.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.record.receiving_account_id</code>.
     */
    public void setReceivingAccountId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.record.receiving_account_id</code>.
     */
    public Integer getReceivingAccountId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Long, String, LocalDateTime, String, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Long, String, LocalDateTime, String, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Record.RECORD.ID;
    }

    @Override
    public Field<Long> field2() {
        return Record.RECORD.AMOUNT;
    }

    @Override
    public Field<String> field3() {
        return Record.RECORD.TYPE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Record.RECORD.RECORD_DATE;
    }

    @Override
    public Field<String> field5() {
        return Record.RECORD.DESCRIPTION;
    }

    @Override
    public Field<Integer> field6() {
        return Record.RECORD.CATEGORY_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Record.RECORD.ACCOUNT_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Record.RECORD.RECEIVING_ACCOUNT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAmount();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public LocalDateTime component4() {
        return getRecordDate();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Integer component6() {
        return getCategoryId();
    }

    @Override
    public Integer component7() {
        return getAccountId();
    }

    @Override
    public Integer component8() {
        return getReceivingAccountId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAmount();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public LocalDateTime value4() {
        return getRecordDate();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Integer value6() {
        return getCategoryId();
    }

    @Override
    public Integer value7() {
        return getAccountId();
    }

    @Override
    public Integer value8() {
        return getReceivingAccountId();
    }

    @Override
    public RecordRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RecordRecord value2(Long value) {
        setAmount(value);
        return this;
    }

    @Override
    public RecordRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public RecordRecord value4(LocalDateTime value) {
        setRecordDate(value);
        return this;
    }

    @Override
    public RecordRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public RecordRecord value6(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public RecordRecord value7(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public RecordRecord value8(Integer value) {
        setReceivingAccountId(value);
        return this;
    }

    @Override
    public RecordRecord values(Integer value1, Long value2, String value3, LocalDateTime value4, String value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecordRecord
     */
    public RecordRecord() {
        super(Record.RECORD);
    }

    /**
     * Create a detached, initialised RecordRecord
     */
    public RecordRecord(Integer id, Long amount, String type, LocalDateTime recordDate, String description, Integer categoryId, Integer accountId, Integer receivingAccountId) {
        super(Record.RECORD);

        setId(id);
        setAmount(amount);
        setType(type);
        setRecordDate(recordDate);
        setDescription(description);
        setCategoryId(categoryId);
        setAccountId(accountId);
        setReceivingAccountId(receivingAccountId);
        resetChangedOnNotNull();
    }
}
