ALTER TABLE account
    ALTER COLUMN type SET DATA TYPE VARCHAR(20);

ALTER TABLE account
    ALTER COLUMN color SET DATA TYPE VARCHAR(20);

ALTER TABLE category
    ALTER COLUMN color SET DATA TYPE VARCHAR(20);